[project]
name = "mlp"
version = "0.1.0"
description = "MLP project"
readme = "README.md"
requires-python = ">=3.19"

dependencies = [
    "numpy==2.3.3",
    "scikit-learn==1.7.2",
    "torch==2.4.0",
    "dgl @ https://data.dgl.ai/wheels/torch-2.4/cu124/repo.html",
]

